dbmspro/dbmspro/urls.py
'''
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('safenet.urls')),
]
'''

from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from safenet import views
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^special/',views.special,name='special'),
    url(r'^safenet/',include('safenet.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
]

dbmspro/safenet/urls.py
'''from django.urls import path

from . import views
urlpatterns = [
    path('',views.index, name="home"),
    path('plan_info',views.plan_info, name="plan_info"),
    path('login',views.login, name="login"),
    path('signup',views.signup, name="signup"),
]'''

from django.conf.urls import url
from safenet import views
# SET THE NAMESPACE!
app_name = 'safenet'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    url(r'^plan_info/$',views.plan_info_from_db, name="plan_info_from_db"),
    url(r'^signup/$',views.signup,name='signup'),
    url(r'^user_login/$',views.user_login,name='user_login'),
    url(r'^your_plans/$',views.your_plans,name='your_plans'),
]

dbmspro/safenet/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User

# Create your models here.

def __str__(self):
  return self.user.username

class User_Info(models.Model):
	usid = models.IntegerField(primary_key=True)
	name = models.CharField(max_length=30)
	email = models.CharField(max_length=50)
	password = models.CharField(max_length=100)

class Bookings(models.Model):
	urlid = models.CharField(max_length=5, primary_key=True)
	name = models.CharField(max_length=50)
	url = models.CharField(max_length=100)

class ECommerce(models.Model):
	urlid = models.CharField(max_length=5, primary_key=True)
	name = models.CharField(max_length=50)
	url = models.CharField(max_length=100)

class Entertainment(models.Model):
	urlid = models.CharField(max_length=5, primary_key=True)
	name = models.CharField(max_length=50)
	url = models.CharField(max_length=100)

class Games(models.Model):
	urlid = models.CharField(max_length=5, primary_key=True)
	name = models.CharField(max_length=50)
	url = models.CharField(max_length=100)

class Illegal(models.Model):
	urlid = models.CharField(max_length=5, primary_key=True)
	name = models.CharField(max_length=50)
	url = models.CharField(max_length=100)

class Messaging(models.Model):
	urlid = models.CharField(max_length=5, primary_key=True)
	name = models.CharField(max_length=50)
	url = models.CharField(max_length=100)

class News(models.Model):
	urlid = models.CharField(max_length=5, primary_key=True)
	name = models.CharField(max_length=50)
	url = models.CharField(max_length=100)

class SocialMedia(models.Model):
	urlid = models.CharField(max_length=5, primary_key=True)
	name = models.CharField(max_length=50)
	url = models.CharField(max_length=100)

class Plan(models.Model):
	usid = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, primary_key=True)
	bookings = models.CharField(max_length=100)
	ecommerce = models.CharField(max_length=100)
	entertainment = models.CharField(max_length=100)
	games = models.CharField(max_length=100)
	illegal = models.CharField(max_length=100)
	messaging = models.CharField(max_length=100)
	news = models.CharField(max_length=100)
	socialMedia = models.CharField(max_length=100)

class Custom(models.Model):
	usid = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	block = models.CharField(max_length=100)
	redirect = models.CharField(max_length=100)

class Meta:
	unique_together = [['usid', 'block']]

dbmspro/safenet/forms.py
from django import forms
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','password','email')

dbmspro/safenet/views.py
'''from django.shortcuts import render


def index(request):
	return render(request,'safenet/index.html')

def plan_info(request):
	return render(request,'safenet/plan_info.html')

def login(request):
	return render(request,'safenet/login.html')

def signup(request):
	return render(request,'safenet/signup.html')
'''


from django.shortcuts import render
from safenet.forms import UserForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from safenet.models import Plan, Custom, Bookings, ECommerce, Entertainment, Games, Illegal, Messaging, News, SocialMedia
import safenet.utils as utils
import os
import platform
import json

def index(request):
	return render(request,'safenet/index.html')

def plan_info(request):
	return render(request,'safenet/plan_info.html')

@login_required
def special(request):
	return HttpResponse("You are logged in !")

@login_required
def user_logout(request):
	utils.unblockSites()
	logout(request)
	return HttpResponseRedirect(reverse('index'))

@login_required
def yourplans(request):
	return render(request, 'safenet/your_plans.html')

def signup(request):
	signedup = False
	if request.method == 'POST':
		user_form = UserForm(data=request.POST)
		if user_form.is_valid(): 
			user = user_form.save()
			user.set_password(user.password)
			user.save()
			signedup = True
		else:
			print(user_form.errors)
	else:
		user_form = UserForm()
	return render(request,'safenet/signup.html',
						  {'user_form':user_form,
						   'signedup':signedup})

def user_login(request):
	if request.method == 'POST':
		username = request.POST.get('username')
		password = request.POST.get('password')
		user = authenticate(username=username, password=password)
		if user:
			if user.is_active:
				login(request,user)

				OS = platform.system()

				host_file = None

				if OS == 'Windows':
					host_file = 'C:\\Windows\\System32\\drivers\\etc\\hosts'
				elif OS == 'Darwin':
					host_file = '/etc/hosts'
				else:
					host_file = '/etc/hosts'

				cmd_str = 'sudo cp ' + host_file + ' ../etc_hosts'
				os.system(cmd_str)

				try:
					plan_urls = Plan.objects.get(usid=request.user.id)
					custom_urls = Custom.objects.filter(usid=request.user.id)

					urls = [plan_urls.bookings, plan_urls.ecommerce, plan_urls.entertainment, plan_urls.games, plan_urls.illegal, plan_urls.messaging, plan_urls.news, plan_urls.socialMedia]
					for url in custom_urls:
						urls.append(url.block)
						urls.append(url.redirect)
					b = Bookings.objects.raw('select * from safenet_bookings')
					ec = ECommerce.objects.raw('select * from safenet_ecommerce')
					e = Entertainment.objects.raw('select * from safenet_entertainment')
					g = Games.objects.raw('select * from safenet_games')
					il = Illegal.objects.raw('select * from safenet_illegal')
					m = Messaging.objects.raw('select * from safenet_messaging')
					n = News.objects.raw('select * from safenet_news')
					s = SocialMedia.objects.raw('select * from safenet_socialmedia')

					utils.blockSites(urls, b, ec, e, g, il, m, n, s)
					
				except:
					plan_urls=None
					custom_urls=None
				return HttpResponseRedirect(reverse('index'))
			else:
				return HttpResponse("Your account was inactive.")
		else:
			print("Someone tried to login and failed.")
			print("They used username: {} and password: {}".format(username,password))
			return HttpResponse("Invalid login details given")
	else:
		return render(request, 'safenet/login.html', {})

def your_plans(request):
	current_user = request.user
	if request.method == 'POST':
		try:
			plan_urls = Plan.objects.get(usid=current_user)
			custom_urls = Custom.objects.filter(usid=current_user)

			urls = [plan_urls.bookings, plan_urls.ecommerce, plan_urls.entertainment, plan_urls.games, plan_urls.illegal, plan_urls.messaging, plan_urls.news, plan_urls.socialMedia]
			for url in custom_urls:
						urls.append(url.block)
						urls.append(url.redirect)

			if plan_urls:
				plan_urls.delete()
			if custom_urls:
				custom_urls.delete()
		except:
			pass

		bookings = 'NULL'
		if request.POST.get('c1'):
			bookings = 'TRUE'
			if request.POST.get('s1'):
				bookings = request.POST.get('u1')
		ecommerce = 'NULL'
		if request.POST.get('c2'):
			ecommerce = 'TRUE'
			if request.POST.get('s2'):
				ecommerce = request.POST.get('u2')
		entertainment = 'NULL'
		if request.POST.get('c3'):
			entertainment = 'TRUE'
			if request.POST.get('s3'):
				entertainment = request.POST.get('u3')
		games = 'NULL'
		if request.POST.get('c4'):
			games = 'TRUE'
			if request.POST.get('s4'):
				games = request.POST.get('u4')
		illegal = 'NULL'
		if request.POST.get('c5'):
			illegal = 'TRUE'
			if request.POST.get('s5'):
				illegal = request.POST.get('u5')
		messaging = 'NULL'
		if request.POST.get('c6'):
			messaging = 'TRUE'
			if request.POST.get('s6'):
				messaging = request.POST.get('u6')
		news = 'NULL'
		if request.POST.get('c7'):
			news = 'TRUE'
			if request.POST.get('s7'):
				news = request.POST.get('u7')
		social_media = 'NULL'
		if request.POST.get('c8'):
			social_media = 'TRUE'
			if request.POST.get('s8'):
				social_media = request.POST.get('u8')

		plan_urls = Plan(usid=current_user, bookings=bookings, ecommerce=ecommerce, entertainment=entertainment,
			games=games, illegal=illegal, messaging=messaging, news=news, socialMedia=social_media)
		plan_urls.save()

		# Also do for without www.

		block1 = block2 = block3 = 'NULL'
		redirect1 = redirect2 = redirect3 = 'NULL'
		if request.POST.get('c9'):
			block1 = request.POST.get('c9')
			if request.POST.get('s9'):
				redirect1 = request.POST.get('u9')
		if request.POST.get('c10'):
			block2 = request.POST.get('c10')
			if request.POST.get('s10'):
				redirect2 = request.POST.get('u10')
		if request.POST.get('c11'):
			block3 = request.POST.get('c11')
			if request.POST.get('s11'):
				redirect3 = request.POST.get('u11')

		block1 = block1.replace('https://', '').replace('http://', '')
		redirect1 = redirect1.replace('https://', '').replace('http://', '')
		block2 = block2.replace('https://', '').replace('http://', '')
		redirect2 = redirect2.replace('https://', '').replace('http://', '')
		block3 = block3.replace('https://', '').replace('http://', '')
		redirect3 = redirect3.replace('https://', '').replace('http://', '')
				
		if block1 != 'NULL':
			url1 = Custom(usid=current_user, block=block1, redirect=redirect1)
			url1.save()
		if block2 != 'NULL':
			url2 = Custom(usid=current_user, block=block2, redirect=redirect2)
			url2.save()
		if block3 != 'NULL':
			url3 = Custom(usid=current_user, block=block3, redirect=redirect3)
			url3.save()

		new = list()
		new.append(plan_urls.bookings)
		new.append(plan_urls.ecommerce)
		new.append(plan_urls.entertainment)
		new.append(plan_urls.games)
		new.append(plan_urls.illegal)
		new.append(plan_urls.messaging)
		new.append(plan_urls.news)
		new.append(plan_urls.socialMedia)
		new.append(block1)
		new.append(redirect1)
		new.append(block2)
		new.append(redirect2)
		new.append(block3)
		new.append(redirect3)
		b = Bookings.objects.raw('select * from safenet_bookings')
		ec = ECommerce.objects.raw('select * from safenet_ecommerce')
		e = Entertainment.objects.raw('select * from safenet_entertainment')
		g = Games.objects.raw('select * from safenet_games')
		il = Illegal.objects.raw('select * from safenet_illegal')
		m = Messaging.objects.raw('select * from safenet_messaging')
		n = News.objects.raw('select * from safenet_news')
		s = SocialMedia.objects.raw('select * from safenet_socialmedia')

		with open('./safenet/static/safenet/javascript/urls.json', 'w') as f:
			json.dump(new, f)

		print(new)
		with open('./safenet/static/safenet/javascript/urls.json', 'w') as f:
				json.dump(new, f)

		utils.updateBlockedSites(new, b, ec, e, g, il, m, n, s)
		return render(request, 'safenet/your_plans.html', {})
	else:
		try:
			plan_urls = Plan.objects.get(usid=current_user)
			custom_urls = Custom.objects.filter(usid=current_user)

			urls = [plan_urls.bookings, plan_urls.ecommerce, plan_urls.entertainment, plan_urls.games, plan_urls.illegal, plan_urls.messaging, plan_urls.news, plan_urls.socialMedia]
			for url in custom_urls:
						urls.append(url.block)
						urls.append(url.redirect)
			with open('./safenet/static/safenet/javascript/urls.json', 'w') as f:
				json.dump(urls, f)

		except:
			urls = ['NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL']
			with open('./safenet/static/safenet/javascript/urls.json', 'w') as f:
				json.dump(urls, f)

		return render(request, 'safenet/your_plans.html', {})

def plan_info_from_db(request):
	booking_sites = Bookings.objects.raw('select urlid, name from safenet_bookings')
	ecommerce_sites = ECommerce.objects.raw('select urlid, name from safenet_ecommerce')
	entertainment_sites = Entertainment.objects.raw('select urlid, name from safenet_entertainment')
	games_sites = Games.objects.raw('select urlid, name from safenet_games')
	illegal_sites = Illegal.objects.raw('select urlid,name from safenet_illegal')
	messaging_sites = Messaging.objects.raw('select urlid, name from safenet_messaging')
	news_sites = News.objects.raw('select urlid, name from safenet_news')
	socialmedia_sites = SocialMedia.objects.raw('select urlid, name from safenet_socialmedia')
	return render(request, 'safenet/plan_info_db.html',
	{
		'bookings': booking_sites,
		'ecommerce' : ecommerce_sites,
		'entertainment': entertainment_sites,
		'games': games_sites,
		'illegal': illegal_sites,
		'messaging': messaging_sites,
		'news': news_sites,
		'socialmedia': socialmedia_sites })

dbmspro/safenet/templates/safenet/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

	<title>Safe-Internet</title>
  </head>
  <body>
	<nav class="navbar navbar-expand-lg navbar-light bg-light" >
		<div class="container">
			<a class="navbar-brand" href="#">
					<img src="{% static 'safenet/images/SafeNetIcon.jpg'%}" width="50" height="50" alt="">
					Safe-Internet</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarNav">
				<ul class="navbar-nav" mx-auto>
					<li class="nav-item active">
						<a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'safenet:plan_info_from_db' %}">Plans</a>
					</li>
					{% if user.is_authenticated %}
            		<li class="nav-item">
						<a class="nav-link" href="{% url 'logout' %}">Logout</a>
					</li>
          			{% else %}
            		<li class="nav-item">
						<a class="nav-link" href="{% url 'safenet:user_login' %}">Login</a>
					</li>
          			{% endif %}
					<!-- <li class="nav-item">
						<a class="nav-link" href="{% url 'safenet:user_login' %}">LogIn</a>
					</li> -->
					{% if user.is_authenticated %}
					<li class="nav-item">
						<a class="nav-link" href="{% url 'safenet:your_plans' %}">YourPlans</a>
					</li>
					{% else %}
					<li class="nav-item">
						<a class="nav-link" href="{% url 'safenet:signup' %}">SignUp</a>
					</li>
					{% endif %}
					
				</ul>
			</div>
		</div>
	</nav>
    
    {% block content %}
    {% endblock %}
	
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

dbmspro/safenet/templates/safenet/index.html
{% extends 'safenet/base.html' %}
{% load static %}

{% block content %}
<img src="{% static 'safenet/images/Internet-Safety.jpg' %}" width=100% height = 500px>

{% if user.is_authenticated %}
        <h2>Hello {{ user.username }}</h2>
{% else %}
        <h2>Register or Login if you'd like to</h2>
{% endif %}
	
<!-- <h1>Log In or Sign Up</h1>
<form>
	<input type="button" value="Log In"
	onclick="window.location.href='./user_login.html'"/>
	<input type="button" value="Sign Up"
	onclick="window.location.href='./signup.html'"/>
</form> -->
{% endblock %}

dbmspro/safenet/templates/safenet/login.html
{% extends 'safenet/base.html' %}
{% load static %}

{% block content %}
<h1 style="padding-left: 20px;"">Log In</h1>
<div class="loginform" style="padding-left: 20px;">
	<form method="post" action="{% url 'safenet:user_login' %}">
		{% csrf_token %}
		<fieldset>
			<legend style="padding-top: 20px; padding-bottom: 10px;">Log-In Information</legend>
				<label for="username">Username:</label>
				<input type="text" name="username" placeholder="Username">
				<br><br>
				<label for="password">Password:</label>
          		<input type="password" name="password" placeholder="Password">
				<br><br>
				<input type="submit" value="Login">
		</fieldset>
	</form>
</div>
{% endblock%}
	

dbmspro/safenet/templates/safenet/plan_info.html
{% extends 'safenet/base.html' %}
{% load static %}

{% block content %}
<div style="padding-left: 20px;">
<h1 style="padding-top: 30px;">Plan Information</h1>
<div>This page aims to give some information about all the plans we provide.</div>
<br>
<h2>Plan 1</h2>
<h3>Bookings</h3>
<p>This plan contains all sites related to booking hotels, flights, movies , etc.
	The sites under this plan are:-
	<ul>
		<li>BookMyShow</li>
		<li>RedBus</li>
		<li>MakeMyTrip</li>
		<li>IRCTC</li>
		<li>Trivago</li>
		<li>Oyo</li>
	</ul>
</p>

<h2>Plan 2</h2>
<h3>Ecommerce</h3>
<p>This plan contains all sites related to ecommerce
	The sites under this plan are:-
	<ul>
		<li>Amazon</li>
		<li>Flipkart</li>
		<li>Myntra</li>
		<li>Jabong</li>
		<li>Snapdeal</li>
		<li>SheIn</li>
	</ul>
</p>

<h2>Plan 3</h2>
<h3>Entertainment</h3>
<p>This plan contains all sites related to Entertainment
	The sites under this plan are:-
	<ul>
		<li>Netflix</li>
		<li>Spotify</li>
		<li>YouTube</li>
		<li>Prime Video</li>
		<li>Prime Music</li>
		<li>Twitch</li>
	</ul>
</p>

<h2>Plan 4</h2>
<h3>Games</h3>
<p>This plan contains all gaming sites 
	The sites under this plan are:-
	<ul>
		<li>Kongregate</li>
		<li>Free Online Games</li>
		<li>Pogo</li>
		<li>MiniClip</li>
		<li>AGame</li>
	</ul>
</p>

<h2>Plan 5</h2>
<h3>Illegal</h3>
<p>This plan contains all illegal sites
	The sites under this plan are:-
	<ul>
		<li>123Movies</li>
		<li>GoMovies</li>
		<li>Popcornflix</li>
		<li>Best Free Streaming</li>
	</ul>
</p>

<h2>Plan 6</h2>
<h3>Messaging</h3>
<p>This plan contains all sites that provide messaging facility
	The sites under this plan are:-
	<ul>
		<li>WhatsApp</li>
		<li>Messanger</li>
		<li>WeChat</li>
		<li>Hike</li>
	</ul>
</p>

<h2>Plan 7</h2>
<h3>News</h3>
<p>This plan contains all news sites 
	The sites under this plan are:-
	<ul>
		<li>Reuters</li>
		<li>Times of India</li>
		<li>The Hindu</li>
		<li>The New York Times</li>
		<li>The Washington Post/li>
	</ul>
</p>

<h2>Plan 8</h2>
<h3>Social Media</h3>
<p>This plan contains all social media sites
	The sites under this plan are:-
	<ul>
		<li>Instagram</li>
		<li>Facebook</li>
		<li>Snapchat</li>
		<li>Twitter</li>
		<li>Reddit</li>
		<li>Tumblr</li>
	</ul>
</p>
</div>
{% endblock %}

dbmspro/safenet/templates/safenet/plan_info_db.html
{% extends 'safenet/base.html' %}
{% load static %}

{% block content %}
<div style="padding-left: 20px;">
<h1 style="padding-top: 30px;">Plan Information</h1>
<div>This page aims to give some information about all the plans we provide.</div>
<br>
<h2>Plan 1</h2>
<h3>Bookings</h3>
<p>This plan contains all sites related to booking hotels, flights, movies , etc.
	The sites under this plan are:-
	<ul>
        {% for site in bookings %}
        <li>{{site.name}}</li>
        {% endfor %}
    </ul>
</p>

<h2>Plan 2</h2>
<h3>Ecommerce</h3>
<p>This plan contains all sites related to ecommerce
	The sites under this plan are:-
	<ul>
        {% for site in ecommerce %}
        <li>{{site.name}}</li>
        {% endfor %}
	</ul>
</p>

<h2>Plan 3</h2>
<h3>Entertainment</h3>
<p>This plan contains all sites related to Entertainment
	The sites under this plan are:-
	<ul>
        {% for site in entertainment %}
        <li>{{site.name}}</li>
        {% endfor %}
	</ul>
</p>

<h2>Plan 4</h2>
<h3>Games</h3>
<p>This plan contains all gaming sites 
	The sites under this plan are:-
	<ul>
        {% for site in games %}
        <li>{{site.name}}</li>
        {% endfor %}	
	</ul>
</p>

<h2>Plan 5</h2>
<h3>Illegal</h3>
<p>This plan contains all illegal sites
	The sites under this plan are:-
	<ul>
        {% for site in illegal %}
        <li>{{site.name}}</li>
        {% endfor %}
	</ul>
</p>

<h2>Plan 6</h2>
<h3>Messaging</h3>
<p>This plan contains all sites that provide messaging facility
	The sites under this plan are:-
	<ul>
        {% for site in messaging %}
        <li>{{site.name}}</li>
        {% endfor %}
	</ul>
</p>

<h2>Plan 7</h2>
<h3>News</h3>
<p>This plan contains all news sites 
	The sites under this plan are:-
	<ul>
        {% for site in news %}
        <li>{{site.name}}</li>
        {% endfor %}
	</ul>
</p>

<h2>Plan 8</h2>
<h3>Social Media</h3>
<p>This plan contains all social media sites
	The sites under this plan are:-
	<ul>
        {% for site in socialmedia %}
        <li>{{site.name}}</li>
        {% endfor %}
	</ul>
</p>
</div>
{% endblock %}

dbmspro/safenet/templates/safenet/signup.html
{% extends 'safenet/base.html' %}
{% load static %}

{% block content %}

{% if signedup %}
        <h1 style="padding-left: 20px;"">Thank you for registering!</h1>
{% else %}
		<div style="padding-left: 20px;">
		<h1>Register Here</h1>
		<br>
		<h3>Just fill out the form.</h3>
		</div>
		
<h3 style="padding-left: 20px;padding-top: 20px;">Sign Up</h3>
<div class="signupform" style="padding-left: 20px;">
	<form method="post" >
		{% csrf_token %}
		{{ user_form.as_p }}
		<input type="submit" name="" value="Signup" action="safenet:signup">
	</form>
</div>
{% endif %}
{% endblock %}